# Generated by Django 3.2.9 on 2022-05-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_comments_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
