# Generated by Django 3.2.9 on 2022-05-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='time',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='news_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_you',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, default=None, max_length=180, null=True),
        ),
    ]
