# Generated by Django 3.2.9 on 2022-05-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comment',
        ),
    ]
