# Generated by Django 3.2.9 on 2022-05-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_profile_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True, default=None, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
