# Generated by Django 3.2.9 on 2022-05-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_rename_topic_topic_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(blank=True, default=None, max_length=18, null=True, unique=True),
        ),
    ]
