# Generated by Django 3.2.9 on 2022-05-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_topic_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='source',
        ),
    ]
