# Generated by Django 3.2.9 on 2022-05-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20220519_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='topic',
        ),
        migrations.AddField(
            model_name='news',
            name='topic',
            field=models.ManyToManyField(null=True, related_name='news_topic', to='news.Topic'),
        ),
    ]
