# Generated by Django 3.2.9 on 2022-05-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20220520_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.ManyToManyField(related_name='news_topic', to='news.Topic'),
        ),
    ]
