# Generated by Django 3.2.9 on 2022-05-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_news_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='topic',
        ),
        migrations.AddField(
            model_name='news',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_topic', to='news.topic'),
        ),
    ]
