# Generated by Django 3.2.9 on 2022-05-24 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20220524_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='readlist',
            field=models.ManyToManyField(blank=True, related_name='readlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
