# Generated by Django 3.2.9 on 2022-05-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_news_readlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Readlist',
        ),
    ]
