# Generated by Django 3.2.9 on 2022-05-25 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_alter_news_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='news_topic', to='news.topic'),
        ),
    ]
