# Generated by Django 3.2.9 on 2022-05-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_alter_news_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='like',
        ),
    ]
