# Generated by Django 3.2.9 on 2022-05-26 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_readlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='readlist',
        ),
        migrations.AddField(
            model_name='profile',
            name='readlist',
            field=models.ManyToManyField(blank=True, related_name='readlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Readlist',
        ),
    ]
