# Generated by Django 3.2.9 on 2022-05-26 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_auto_20220526_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='readlist',
        ),
        migrations.CreateModel(
            name='Readlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_readlist', to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_readlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
