# Generated by Django 3.2.9 on 2022-05-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_auto_20220526_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readlist',
            name='newslist',
        ),
        migrations.AddField(
            model_name='readlist',
            name='newslist',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='news_readlist', to='news.news'),
        ),
    ]
