# Generated by Django 3.2.9 on 2022-05-26 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_auto_20220526_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='readlist',
            field=models.ManyToManyField(blank=True, related_name='news_readlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
